# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: dansullivan/dan-sullivan.co.uk:0.0.2
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: echo "Running..."
      - run: sudo yarn global add grunt-cli
      - run: yarn install
      - run: grunt lambda
      - run: grunt exec:zip_lambda_dscouk
      - run: if [[ ! -z $CIRCLE_PULL_REQUEST ]] ; then cd terraform; terraform init; if ! terraform workspace new pr${CIRCLE_PULL_REQUEST##*/}; then terraform workspace select pr${CIRCLE_PULL_REQUEST##*/}; fi; terraform plan && terraform apply; fi
      - run: if [ $CIRCLE_BRANCH = 'master' ]; then cd terraform; terraform init; terraform plan && terraform apply; fi
      - run: grunt s3cf
      - run: if [[ ! -z $CIRCLE_PULL_REQUEST ]] ; then BRANCH_PR=pr${CIRCLE_PULL_REQUEST##*/}; else BRANCH_PR=$CIRCLE_BRANCH; fi; grunt exec:upload_s3cf:$BRANCH_PR
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  build:
    jobs:
      - build
